---
apiVersion: v1
kind: ConfigMap
metadata:
  name: udraw-nginx
data:
  udraw.conf: |
    upstream canvasapi { server localhost:3000 fail_timeout=10s; }
    upstream socketio  { server localhost:3001 fail_timeout=10s; }

    server {
      listen 80 default_server;
      index index.html;

      location /canvases/ {
        proxy_pass            http://canvasapi;
        proxy_read_timeout    90;
        proxy_connect_timeout 90;
        proxy_redirect        off;
        proxy_set_header      Host $host;
        proxy_set_header      X-Real-IP $remote_addr;
        proxy_set_header      X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header      Proxy "";
      }

      location /socket.io/ {
        proxy_pass            http://socketio;
        proxy_read_timeout    90;
        proxy_connect_timeout 90;
        proxy_redirect        off;
        proxy_set_header      Host $host;
        proxy_set_header      X-Real-IP $remote_addr;
        proxy_set_header      X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header      Proxy "";
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
      }

      # Our initContainer will copy udraw static files to this mounted volume
      location / { root /usr/share/nginx/html/public/; }
    }

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: udraw-config
  namespace: default
data:
  REDIS_HOST: 'redis'
  REDIS_PORT: '6379'

---
apiVersion: apps/v1beta2 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: udraw
  labels:
    app: udraw
spec:
  replicas: 1
  selector:
    matchLabels:
      app: udraw
  template:
    metadata:
      labels:
        app: udraw
    spec:
      volumes:
      - name: nginx-config
        configMap:
          name: udraw-nginx
      - name: nginx-staticfiles
        emptyDir: {}
      initContainers:
      - name: copy-staticfiles
        image: timatooth/udraw
        imagePullPolicy: IfNotPresent
        command: ['cp', '-rv', '/opt/udraw/public/', '/nginx-staticfiles']
        volumeMounts:
        - name: nginx-staticfiles
          mountPath: /nginx-staticfiles
      containers:
      - name: udraw
        image: timatooth/udraw
        imagePullPolicy: IfNotPresent
        command: ['node', 'server/']
        envFrom:
        - configMapRef:
            name: udraw-config
        ports:
        - containerPort: 3000
        - containerPort: 3001
      - name: nginx
        image: nginx:1.13
        ports:
        - containerPort: 80
        volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx/conf.d
          readOnly: true
        - name: nginx-staticfiles
          mountPath: /usr/share/nginx/html
          readOnly: true

---
apiVersion: apps/v1beta2 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: redis
  labels:
    app: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: redis
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 6379

---
kind: Service
apiVersion: v1
metadata:
  name: redis
spec:
  selector:
    app: redis
  ports:
  - protocol: TCP
    port: 6379

---
kind: Service
apiVersion: v1
metadata:
  name: udraw
spec:
  type: NodePort
  selector:
    app: udraw
  ports:
  - name: canvasapi
    protocol: TCP
    port: 3000
  - name: websocket
    protocol: TCP
    port: 3001
  - name: nginx
    protocol: TCP
    port: 80
    targetPort: 80
