---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "udraw.fullname" . }}-redis
  labels:
    app: {{ .Release.Name }}-redis
    chart: {{ template "udraw.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    componenet: canvasapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-redis
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-redis
        release: {{ .Release.Name }}
    spec:
      containers:
      - name: redis
        image: redis:4
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 6379
          name: redis
          protocol: TCP
