---
kind: Service
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-redis
  labels:
    app: {{ .Release.Name }}-redis
    chart: {{ template "udraw.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    componenet: canvasapi
spec:
  selector:
    app: {{ .Release.Name }}-redis
    release: {{ .Release.Name }}
  ports:
  - port: 6379
    targetPort: redis
    protocol: TCP
    name: redis
