---
apiVersion: apps/v1beta2 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: {{ .Release.Name }}-udrawcanvasapi
  labels:
    app: {{ .Release.Name }}-udrawcanvasapi
spec:
  replicas: {{ .Values.canvasapi.replicas }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-udrawcanvasapi
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-udrawcanvasapi
    spec:
      containers:
      - name: udraw-canvasapi
        image: {{ .Values.image }}
        imagePullPolicy: {{ .Values.imagePullPolicy }}
        command: ['node', 'server']
        envFrom:
        - configMapRef:
            name: {{ .Release.Name }}-udrawconfig
        - secretRef:
            name: {{.Release.Name}}-s3-secret
        env:
        - name: UDRAW_S3_BUCKET
          value: {{ .Values.storage.s3.bucket }}
        - name: AWS_DEFAULT_REGION
          value: {{ .Values.storage.s3.region }}
        ports:
        - containerPort: 3000
