---
kind: Service
apiVersion: v1
metadata:
  name: {{.Release.Name}}-udrawcanvasapi
spec:
  selector:
    app: {{.Release.Name}}-udrawcanvasapi
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
