---
kind: Service
apiVersion: v1
metadata:
  name: {{.Release.Name}}-udrawwebsocket
  labels:
    app: {{ .Release.Name }}-udrawwebsocket
    chart: {{ template "udraw.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    componenet: websocket
spec:
  selector:
    app: {{.Release.Name}}-udrawwebsocket
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3001
