---
# Secrets for Tile Object storage in S3
apiVersion: v1
kind: Secret
metadata:
  name: {{.Release.Name}}-s3-secret
  labels:
    chart: {{ template "udraw.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  AWS_ACCESS_KEY_ID: {{ .Values.storage.s3.AWS_ACCESS_KEY_ID | b64enc }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.storage.s3.AWS_SECRET_ACCESS_KEY | b64enc }}
