---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-udrawwebsocket
  labels:
    app: {{ .Release.Name }}-udrawwebsocket
    chart: {{ template "udraw.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    component: websocket
spec:
  replicas: {{ .Values.websocket.replicas }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-udrawwebsocket
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-udrawwebsocket
    spec:
      containers:
      - name: udraw-websocket
        image: {{ .Values.image }}
        imagePullPolicy: {{ .Values.imagePullPolicy }}
        command: ['node', 'server']
        envFrom:
        - configMapRef:
            name: {{ .Release.Name }}-udrawconfig
        ports:
        - containerPort: 3001
