---
apiVersion: apps/v1beta2 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: {{ .Release.Name }}-udraw
  labels:
    app: {{ .Release.Name }}-udraw
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-udraw
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-udraw
    spec:
      volumes:
      - name: nginx-config
        configMap:
          name: {{ .Release.Name }}-udrawnginxconfig
      - name: nginx-staticfiles
        emptyDir: {}
      initContainers:
      - name: copy-staticfiles
        image: timatooth/udraw
        imagePullPolicy: IfNotPresent
        command: ['cp', '-rv', '/opt/udraw/public/', '/nginx-staticfiles']
        volumeMounts:
        - name: nginx-staticfiles
          mountPath: /nginx-staticfiles
      containers:
      - name: udraw
        image: timatooth/udraw
        imagePullPolicy: IfNotPresent
        command: ['node', 'server']
        envFrom:
        - configMapRef:
            name: {{ .Release.Name }}-udrawconfig
        - secretRef:
            name: {{.Release.Name}}-s3-secret
        ports:
        - containerPort: 3000
        - containerPort: 3001
      - name: nginx
        image: nginx:1.13-alpine
        ports:
        - containerPort: 80
          name: http
        volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx/conf.d
          readOnly: true
        - name: nginx-staticfiles
          mountPath: /usr/share/nginx/html
          readOnly: true
