---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-udrawnginxconfig
data:
  udraw.conf: |
    upstream canvasapi { server localhost:3000 fail_timeout=10s; }
    upstream socketio  { server localhost:3001 fail_timeout=10s; }

    server {
      listen 80 default_server;
      index index.html;

      location /canvases/ {
        proxy_pass            http://canvasapi;
        proxy_read_timeout    90;
        proxy_connect_timeout 90;
        proxy_redirect        off;
        proxy_set_header      Host $host;
        proxy_set_header      X-Real-IP $remote_addr;
        proxy_set_header      X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header      Proxy "";
      }

      location /socket.io/ {
        proxy_pass            http://socketio;
        proxy_read_timeout    90;
        proxy_connect_timeout 90;
        proxy_redirect        off;
        proxy_set_header      Host $host;
        proxy_set_header      X-Real-IP $remote_addr;
        proxy_set_header      X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header      Proxy "";
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
      }

      # Our initContainer will copy udraw static files to this mounted volume
      location / { root /usr/share/nginx/html/public/; }
    }
