service: udraw-canvasapi

plugins:
  # https://www.npmjs.com/package/serverless-apigw-binary
  - serverless-apigw-binary

provider:
  name: aws
  endpointType: REGIONAL
  runtime: nodejs8.10
  region: ap-southeast-2
  stage: dev
  environment:
    UDRAW_S3_BUCKET: udraw-tiles

  iamRoleStatements:
    - Effect: Allow
      Action:
      - s3:ListBucket
      Resource:
      - 'arn:aws:s3:::udraw-tiles'
    - Effect: Allow
      Action:
      - s3:PutObject
      - s3:GetObject
      Resource:
      - 'arn:aws:s3:::udraw-tiles/*'

# you can add packaging information here
#package:
#  include:
#    - include-me.js
#    - include-me-dir/**
#  exclude:
#    - exclude-me.js
#    - exclude-me-dir/**

custom:
  # https://www.npmjs.com/package/serverless-apigw-binary
  apigwBinary:
    types:
      - '*/*'

functions:
  canvas:
    description: Function for Udraw Canvas Tile API
    memorySize: 128
    handler: handler.main
    events:
      - http:
          path: /{proxy+}
          method: GET
          cors: true
          #contentHandling: CONVERT_TO_BINARY
      - http:
          path: /{proxy+}
          method: PUT
          cors: true
          #contentHandling: CONVERT_TO_BINARY
      - http:
          path: /{proxy+}
          method: OPTIONS
          cors: true

#    Define function environment variables here
#    environment:
#      variable2: value2

# you can add CloudFormation resource templates here
resources:
  Description: udraw Canvas Tile API serverless stack
#  Resources:
#    NewResource:
#      Type: AWS::S3::Bucket
#      Properties:
#        BucketName: my-new-bucket
#  Outputs:
#     NewOutput:
#       Description: "Description for the output"
#       Value: "Some output value"
