---
# image to pull from DockerHub
image: timatooth/udraw:latest
imagePullPolicy: Always

canvasapi:
  replicas: 2

websocket:
  # We are currently limited here due to socket.io
  # redis-pub-sub adapter is one option.
  # I might consider NATS messaging server
  replicas: 1

ingress:
  # install stable/nginx-ingress helm chart with this release
  # see 'nginx-ingress' section for configuration
  install: true
  # create an Ingress rule for udraw
  enabled: true
  # URL to address your udraw installation
  hostname: udraw.me
  annotations:
    kubernetes.io/ingress.class: nginx

#### Nginx Ingress Controller subchart settings
# This only applys if you have set "ingress.install: true"
nginx-ingress:
  controller:
    # Bind port 80, 443 to the host machine
    hostNetwork: true
    service:
      type: NodePort

# udraw tile persistent storage
storage:
  # currently only doing S3
  type: s3

  s3:
    region: 'ap-southeast-2'
    bucket: ''
    AWS_ACCESS_KEY_ID: ''
    AWS_SECRET_ACCESS_KEY: ''
